#!/usr/bin/env bash

# Jump to dotfiles.
alias dotfiles="cd ${DOTFILES}"

# Hack to auto expand aliases in sudo.
alias sudo="sudo "

# Because sometimes you gotta be harsh.
alias fucking="sudo"

# And sometimes you gotta be nice.
alias please="sudo"

# Get my IP Address.
alias ip="curl ifconfig.co"

# Run remote commands over ssh.
alias remote="ssh $1 -T $2"

# Use hub over git.
alias git="hub"