#!/usr/bin/env bash

# Jump to dotfiles.
alias dotfiles="cd ${DOTFILES}"

# Hack to auto expand aliases in sudo.
alias sudo="sudo "

# Because sometimes you gotta be harsh.
alias fucking="sudo"

# And sometimes you gotta be nice.
alias please="sudo"

# Get my IP Address.
alias ip="curl -s ip.appspot.com; echo"

# Run remote commands over ssh.
alias remote="ssh $1 -T $2"

# Use my npm. It's better. :)
alias npm="npm-as"

# Use my docker. It's better. :)
alias docker="my-docker"

# MacVim > terminal Vim.
alias vim="mvim"
