tap "aniftyco/cask"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "cloc"
brew "composer"
brew "curl"
brew "direnv"
brew "dnsmasq", restart_service: true
brew "fish"
brew "git"
brew "git-lfs"
brew "sqlite"
brew "go"
brew "httpie"
brew "hub"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "nginx", restart_service: true
brew "php", restart_service: true
brew "postgresql", restart_service: true
brew "redis", restart_service: true
brew "rsync"
brew "telnet"
brew "terminal-notifier"
brew "toilet"
brew "tree"
brew "vim"
brew "watchman"
brew "wget"
brew "wp-cli"
brew "yarn"
brew "zeromq"
brew "zsh"
brew "zsh-autosuggestions"
cask "brave-browser"
cask "cinch"
cask "cleanmymac"
cask "dropbox"
cask "figma"
cask "font-fira-code"
cask "google-chrome-canary"
cask "kitematic"
cask "lastfm"
cask "microsoft-edge-dev"
cask "microsoft-office"
cask "microsoft-teams"
cask "mosaic"
cask "obs"
cask "sketch-toolbox"
cask "stay"
cask "sublime-text"
cask "synergy"
cask "telegram"
cask "timing"
cask "transmit4"
cask "unetbootin"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "zoomus"
mas "Captured", id: 414675451
mas "GarageBand", id: 682658836
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Sip", id: 507257563
mas "Xcode", id: 497799835
