tap "heroku/brew"
tap "homebrew/boneyard"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/php"
tap "homebrew/services"
tap "homebrew/versions"
brew "sqlite"
brew "asciinema"
brew "cloc"
brew "composer"
brew "curl"
brew "dnsmasq", restart_service: true
brew "git"
brew "git-lfs"
brew "go"
brew "httpie"
brew "hub"
brew "hugo"
brew "jq"
brew "kubernetes-cli"
brew "mariadb", restart_service: true
brew "mas"
brew "nginx", restart_service: true
brew "node@8", link: true
brew "php", restart_service: true
brew "postgresql", args: ["with-python"], restart_service: true
brew "redis", restart_service: true
brew "rsync"
brew "speedtest-cli"
brew "telnet"
brew "terminal-notifier"
brew "tmux"
brew "tree"
brew "vim"
brew "watchman"
brew "wget"
brew "wp-cli"
brew "yarn"
brew "zsh"
brew "zsh-autosuggestions"
cask "1password"
cask "android-studio"
cask "brave"
cask "cinch"
cask "cleanmymac"
cask "command-tab-plus"
cask "daisydisk"
cask "discord"
cask "docker"
cask "dropbox"
cask "fantastical"
cask "figma"
cask "filezilla"
cask "firefox"
cask "fluid"
cask "font-fira-code"
cask "google-chrome"
cask "google-chrome-canary"
cask "graphiql"
cask "graphql-playground"
cask "harvest"
cask "imageoptim"
cask "iterm2"
cask "java8"
cask "kap"
cask "mosaic"
cask "ngrok"
cask "nucleo"
cask "postico"
cask "postman"
cask "safari-technology-preview"
cask "sequel-pro"
cask "shimo"
cask "sketch"
cask "sketch-toolbox"
cask "skype"
cask "slack"
cask "smartsvn"
cask "stay"
cask "textual"
cask "timing"
cask "transmit4"
cask "vagrant"
cask "vanilla"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "vmware-horizon-client"
cask "zoomus"
mas "Captured", id: 414675451
mas "GAget", id: 968487158
mas "Irvue", id: 1039633667
mas "Keynote", id: 409183694
mas "Medis", id: 1063631769
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Sip", id: 507257563
mas "Spark", id: 1176895641
mas "Things3", id: 904280696
mas "Trello", id: 1278508951
mas "Tweetbot", id: 1384080005
mas "Xcode", id: 497799835
