tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "awscli"
brew "dnsmasq", restart_service: true
brew "doctl"
brew "fish"
brew "git"
brew "helm"
brew "httpie"
brew "jq"
brew "mas"
brew "node@12", link: true
brew "postgresql", restart_service: true
brew "redis", restart_service: true
brew "watchman"
brew "wget"
brew "yarn"
cask "avibrazil-rdm"
cask "brave-browser"
cask "cleanmymac"
cask "docker"
cask "figma"
cask "firefox"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "google-chrome-canary"
cask "microsoft-edge-beta"
cask "microsoft-edge-dev"
cask "mjml"
cask "mosaic"
cask "postman"
cask "ringcentral"
cask "ringcentral-meetings"
cask "slack"
cask "streamlabs-obs"
cask "tableplus"
cask "telegram"
cask "visual-studio-code"
cask "zoomus"
mas "Fantastical", id: 975937182
mas "Sip", id: 507257563
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835
