import { homedir } from "node:os";
import { join } from "node:path";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import type { CorrectionGroup } from "./insights/corrections.js";
import type { PatternFinding } from "./insights/patterns.js";

const DOTFILES = process.env.DOTFILES || join(homedir(), ".files");
const RULES_DIR = join(DOTFILES, "claude", "rules");
const SKILLS_DIR = join(DOTFILES, "claude", "skills");

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "untitled";
}

export interface Scaffold {
  path: string;
  content: string;
  exists: boolean;
}

export function scaffoldFeedback(group: CorrectionGroup): Scaffold {
  const slug = slugify(group.marker);
  const path = join(RULES_DIR, `feedback-${slug}.md`);

  // Pull up to 3 representative examples for the body.
  const examples = group.findings.slice(0, 3);

  const body = `# Feedback: ${group.marker}

**Detected ${group.count}× across your conversation history.**

## The pattern

When Claude does X, you respond with phrasing matching \`${group.marker}\`. This is a recurring correction — encode it as a durable rule so it doesn't keep happening.

## What you push back on

${examples
    .map(
      (e) => `- _"${e.userText.replace(/\s+/g, " ").slice(0, 200)}"_${e.precedingAssistant ? `\n  - context: \`${e.precedingAssistant.replace(/\s+/g, " ").slice(0, 160)}\`` : ""}`,
    )
    .join("\n")}

## The rule

> _Replace this paragraph with the rule you want Claude to follow. Be specific about the trigger and the desired behavior. Reference the prime-directives style if applicable._

## Why

> _Why does this matter? What goes wrong when Claude doesn't follow this?_

## How to apply

> _When does this rule kick in? Concrete triggers, not abstract principles._

---

_Generated by \`cpanel\` Insights from ${group.count} occurrence(s)._
`;

  return { path, content: body, exists: existsSync(path) };
}

export function scaffoldSkill(pattern: PatternFinding): Scaffold {
  // Derive a name from the dominant tool in the sequence.
  const dominant = mostCommonStep(pattern.sequence);
  const baseName = `pattern-${slugify(dominant)}-${pattern.sequence.length}step`;
  const dir = join(SKILLS_DIR, baseName);
  const path = join(dir, "SKILL.md");

  const stepsList = pattern.sequence.map((s, i) => `${i + 1}. \`${s}\``).join("\n");

  const body = `---
name: ${baseName}
description: "Recurring ${pattern.sequence.length}-step workflow detected across ${pattern.sessions} sessions (${pattern.occurrences} occurrences). Replace this description with what the workflow accomplishes and when to invoke it."
user-invocable: false
---

# ${baseName}

cpanel detected this tool sequence happening **${pattern.occurrences} times** across **${pattern.sessions} sessions**:

${stepsList}

## When to invoke

> _Replace this with the trigger conditions. What is the user trying to accomplish when this sequence happens? Match the existing skill style in this repo._

## Workflow

> _Translate the tool sequence into a step-by-step workflow. Each step should describe the intent, not just the tool name._

${pattern.sequence
    .map(
      (s, i) => `### Step ${i + 1}

\`\`\`
${s}
\`\`\`

> _Describe what this step does and what to look for in the output before moving to the next step._`,
    )
    .join("\n\n")}

## Recent examples

${pattern.examples
    .map((ex) => `- \`${ex.projectCwd}\` (session \`${ex.sessionId.slice(0, 8)}\`)`)
    .join("\n")}

---

_Generated by \`cpanel\` Insights. If this would be better as a bin script than a skill, copy the workflow to \`~/.files/bin/${baseName}\` and delete this directory._
`;

  return { path, content: body, exists: existsSync(path) };
}

function mostCommonStep(steps: string[]): string {
  const counts = new Map<string, number>();
  for (const s of steps) counts.set(s, (counts.get(s) ?? 0) + 1);
  let best = steps[0] ?? "tool";
  let max = 0;
  for (const [s, n] of counts) if (n > max) { max = n; best = s; }
  // Strip the discriminator after `:` for a cleaner slug.
  return best.split(":")[0]!;
}

export function writeScaffold(scaffold: Scaffold): void {
  const dir = scaffold.path.substring(0, scaffold.path.lastIndexOf("/"));
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(scaffold.path, scaffold.content, "utf8");
}
