; Loaded from php-fpm.d after www.conf, so these add to the stock config

[global]
log_level = error

[www]
php_admin_value[error_reporting] = E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED

;Signal 11 workaround
env['PGGSSENCMODE'] = disable
env['LC_ALL'] = C
